from app.models import workout_exercise
from ..models import db, Routine, Workout, WorkoutExercise, Exercise, Scheme
from sqlalchemy import or_
from flask import jsonify


def routine_builder(questionnaire):
    exercises = Exercise.query.filter(or_(Exercise
                                      .modality == questionnaire.barbell,
                                          Exercise
                                      .modality == questionnaire.dumbbell,
                                          Exercise
                                      .modality == questionnaire.cable,
                                          Exercise
                                      .modality == questionnaire.lever,
                                          Exercise
                                      .modality == "bodyweight",)).all()
    print(exercises)
    movements = {}
    for exercise in exercises:
        print(movements)
        if exercise.movement_id not in movements:
            movements[exercise.movement_id] = exercise.id
    if questionnaire.goal == 'increase':
        routine = Routine(
            user_id=questionnaire.user_id,
            questionnaire_id=questionnaire.id,
            workouts=[
                Workout(
                    order=1,
                    workout_exercises=[
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=18
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=19
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=20
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[6])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[7])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[11])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[1])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[21])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[24])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[23])
                        ),
                        # WorkoutExercise(
                        #     max=0,
                        #     scheme_id=7,
                        #     exercise_id=int(movements[26])
                        # ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[22])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[25])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=105
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=106
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=107
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=108
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=109
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[55])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[56])
                        )
                    ]
                ),
                Workout(
                    order=2,
                    workout_exercises=[
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=18
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=19
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=20
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[8])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[9])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[10])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[2])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[27])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[28])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[31])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[30])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[29])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[32])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=105
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=106
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=107
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=108
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=109
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[55])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[56])
                        )
                    ]
                ),
                Workout(
                    order=3,
                    workout_exercises=[
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=18
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=19
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=20
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[11])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[12])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[13])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[3])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[33])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[34])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[35])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[36])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[37])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[38])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=105
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=106
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=107
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=108
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=109
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[55])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[56])
                        )
                    ]
                ),
                Workout(
                    order=4,
                    workout_exercises=[
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=18
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=19
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=20
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[14])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[15])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[13])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[4])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[28])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[39])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[40])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[41])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[43])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[42])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=105
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=106
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=107
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=108
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=109
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[55])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[56])
                        )
                    ]
                ),
                Workout(
                    order=5,
                    workout_exercises=[
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=18
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=19
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=20
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[16])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[17])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[6])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[5])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[44])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[45])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[46])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[47])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[48])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[49])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=105
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=106
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=107
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=108
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=109
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=9,
                            exercise_id=int(movements[55])
                        ),
                        WorkoutExercise(
                            max=0,
                            scheme_id=7,
                            exercise_id=int(movements[56])
                        )
                    ]
                )
            ]
        )
        db.session.add(routine)
        db.session.commit()
        return routine
    if questionnaire.goal == 'decrease':
        pass
    if questionnaire.goal == 'maintain':
        pass
