"""update tables

Revision ID: 3a09c9761edd
Revises: a93e97e2a5b7
Create Date: 2021-06-07 17:02:19.572497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a09c9761edd'
down_revision = 'a93e97e2a5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercise_results', sa.Column('set', sa.Integer(), nullable=True))
    op.drop_column('workout_exercise_results', 'sets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercise_results', sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('workout_exercise_results', 'set')
    # ### end Alembic commands ###
