"""update questionnaire

Revision ID: 46a892159d7a
Revises: ca683ef5db11
Create Date: 2021-06-08 11:55:33.322380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a892159d7a'
down_revision = 'ca683ef5db11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaires', sa.Column('barbell', sa.String(length=3), nullable=False))
    op.add_column('questionnaires', sa.Column('cable', sa.String(length=3), nullable=False))
    op.add_column('questionnaires', sa.Column('dumbbell', sa.String(length=3), nullable=False))
    op.add_column('questionnaires', sa.Column('lever', sa.String(length=3), nullable=False))
    op.drop_column('questionnaires', 'barbells')
    op.drop_column('questionnaires', 'levers')
    op.drop_column('questionnaires', 'cables')
    op.drop_column('questionnaires', 'dumbbells')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaires', sa.Column('dumbbells', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('questionnaires', sa.Column('cables', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('questionnaires', sa.Column('levers', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.add_column('questionnaires', sa.Column('barbells', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.drop_column('questionnaires', 'lever')
    op.drop_column('questionnaires', 'dumbbell')
    op.drop_column('questionnaires', 'cable')
    op.drop_column('questionnaires', 'barbell')
    # ### end Alembic commands ###
