"""create movement table

Revision ID: a93e97e2a5b7
Revises: ee4275c1f710
Create Date: 2021-06-06 01:50:08.828094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93e97e2a5b7'
down_revision = 'ee4275c1f710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('muscle_group', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('exercises', sa.Column('modality', sa.String(length=50), nullable=False))
    op.add_column('exercises', sa.Column('movement_id', sa.Integer(), nullable=False))
    op.drop_constraint('exercises_name_key', 'exercises', type_='unique')
    op.create_foreign_key(None, 'exercises', 'movements', ['movement_id'], ['id'])
    op.drop_column('exercises', 'type')
    op.drop_column('exercises', 'name')
    op.drop_column('exercises', 'muscle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('muscle', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('exercises', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('exercises', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.create_unique_constraint('exercises_name_key', 'exercises', ['name'])
    op.drop_column('exercises', 'movement_id')
    op.drop_column('exercises', 'modality')
    op.drop_table('movements')
    # ### end Alembic commands ###
