"""adding order to workout exercises

Revision ID: 893a0ba88812
Revises: 888e51558184
Create Date: 2021-06-11 13:12:14.776648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893a0ba88812'
down_revision = '888e51558184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('order', sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_exercises', 'order')
    # ### end Alembic commands ###
