"""update scheme with rest

Revision ID: ca683ef5db11
Revises: 3a09c9761edd
Create Date: 2021-06-07 23:47:26.264463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca683ef5db11'
down_revision = '3a09c9761edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schemes', sa.Column('rest', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schemes', 'rest')
    # ### end Alembic commands ###
